"""caching of avatar hashes

Revision ID: 1eabd35b0
Revises: 2268d867e38
Create Date: 2015-07-09 17:47:22.377900

"""

# revision identifiers, used by Alembic.
revision = '1eabd35b0'
down_revision = '2268d867e38'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
