"""rich text posts

Revision ID: 3cc4db2c510
Revises: 4a0c1bcd40
Create Date: 2015-07-13 15:26:14.203293

"""

# revision identifiers, used by Alembic.
revision = '3cc4db2c510'
down_revision = '4a0c1bcd40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
