"""initial migration

Revision ID: 4c74da45a1
Revises: None
Create Date: 2015-06-15 16:54:25.612552

"""

# revision identifiers, used by Alembic.
revision = '4c74da45a1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
