"""empty message

Revision ID: 57f9f681e6e
Revises: ced4c25c06
Create Date: 2015-07-06 15:43:02.997600

"""

# revision identifiers, used by Alembic.
revision = '57f9f681e6e'
down_revision = 'ced4c25c06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
