"""account confirmation

Revision ID: ced4c25c06
Revises: 2684b26459f
Create Date: 2015-06-23 14:49:35.640867

"""

# revision identifiers, used by Alembic.
revision = 'ced4c25c06'
down_revision = '2684b26459f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
